## DB Actions and Review
With this notebook we'll be performing the actions that the APP requires, also we'll be reviewing that all the actions related with the DB are being executed properly.

In [2]:
from dotenv import load_dotenv
import pymysql
import sqlalchemy
import os
from dotenv import load_dotenv
import pandas as pd

In [3]:
def delete_session():
    try:

        delete_data = f"DELETE FROM session"
        cursor.execute(delete_data)
        
     
        reset_auto_increment = "ALTER TABLE session AUTO_INCREMENT = 1"
        cursor.execute(reset_auto_increment)
        

        db.commit()
        print("All sessions deleted and AUTO_INCREMENT reset to 1.")
    
    except Exception as e:
        db.rollback()  
        print(f"Error: {e}")

In [4]:
# LOAD ALL THE INFORMATION THAT THE APP WILL REQUIRE
load_dotenv()
username = os.getenv("DB_USER")
password = os.getenv("DB_PW")
host = os.getenv("DB_HOST")
port = 3306

In [5]:
#DB CONNECTION
db = pymysql.connect(host = host,
                     user = username,
                     password = password,
                     cursorclass = pymysql.cursors.DictCursor
)

# CURSOR OBJECT WILL EXECUTE ALL THE QUERIES AND FETCH THE DATA
cursor = db.cursor()

In [ ]:
#CREATE THE FIRST VERSION OF THE DEV DB
create_db = '''CREATE DATABASE kpi_database'''
cursor.execute(create_db)

In [6]:
#LET'S CHECK IS BEEN CREATED PROPERLY
cursor.execute('SHOW DATABASES')
cursor.fetchall()

[{'Database': 'information_schema'},
 {'Database': 'kpi_database'},
 {'Database': 'mysql'},
 {'Database': 'performance_schema'},
 {'Database': 'sys'}]

In [7]:
#WE'LL CREATE THE TABLE THAT IS GOING TO FETCH ID SESSION, PROMPT(QUESTION) AND ANSWER.
cursor.connection.commit()
use_db = ''' USE kpi_database'''
cursor.execute(use_db)

0

### TABLE CREATION
1. Table **session** for getting id, id_user, date.  
2. Table **profile** this will pick up the required fields for the prompt, also it will give us researchable insights from the user.  
3. Table **question** this will register the question(prompt).  
4. Table **answers** this will pick the answers from the chat.

In [27]:
create_table = '''
CREATE TABLE session (
    id INT NOT NULL auto_increment,
    id_user INT NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    primary key (id)
)
'''
cursor.execute(create_table)
db.commit()

In [28]:
create_table = '''
CREATE TABLE profile (
    id_profile INT NOT NULL auto_increment,
    id_user INT NOT NULL,
    position VARCHAR(120),
    department VARCHAR(120),
    sector VARCHAR(120),
    primary key (id_profile)
)
'''
cursor.execute(create_table)
db.commit()

In [29]:
create_table = '''
CREATE TABLE user (
    id_user INT NOT NULL,
    primary key (id_user)
)
'''
cursor.execute(create_table)
db.commit()

In [30]:
create_table = '''
CREATE TABLE project (
    id_user INT NOT NULL,
    id_project INT NOT NULL auto_increment,
    project TEXT,
    primary key (id_project)
)
'''
cursor.execute(create_table)
db.commit()

In [31]:
create_table = '''
CREATE TABLE question (
    id_question INT NOT NULL auto_increment,
    id INT NOT NULL,
    question TEXT NOT NULL,
    question_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    primary key (id_question)
)
'''
cursor.execute(create_table)
db.commit()

In [32]:
create_table = '''
CREATE TABLE answer (
    id_answer INT NOT NULL auto_increment,
    id_question INT NOT NULL,
    id INT NOT NULL,
    answer TEXT,
    answer_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    primary key (id_answer)
)
'''
cursor.execute(create_table)
db.commit()

Manual testing

In [22]:
#session

id_user = 999999

insert_data = '''
INSERT INTO session (id_user) 
VALUES (%s)
'''
cursor.execute(insert_data, (id_user))

1

In [33]:
sql = '''SELECT * FROM session'''
cursor.execute(sql)
my_list = cursor.fetchall()
db_pandas = pd.DataFrame(my_list)
db_pandas

   id  id_user                date
0   1   817329 2025-03-02 16:49:06
1   2   746808 2025-03-02 16:55:48
2   3   282055 2025-03-02 16:56:58

In [34]:
#profile

position = "Customer Fullfilment Manager"
department = "After-Sales Department"
sector = "Retail"
project = "Call Center Performance"

insert_data = '''
INSERT INTO profile (id_user, position, department, sector, project) 
VALUES (%s, %s, %s, %s, %s)
'''
cursor.execute(insert_data, (id_user, position, department, sector, project))

NameError: name 'id_user' is not defined

In [35]:
sql = '''SELECT * FROM profile'''
cursor.execute(sql)
my_profile = cursor.fetchall()
db_profile = pd.DataFrame(my_profile)
db_profile

,id_profile,id_user,position,department,sector
0,1,817329,Customer Fulfilment Manager,After Sales,Home Appliances Retail
1,2,746808,Customer Fullfilment Manager,After Sales,Home Appliances Retail
2,3,282055,Customer Fullfilment Manager,After Sales,Retail

In [32]:
# question
id = 1
question = "You're a business analyst expert. I'm a Customer Fullfilment Manager at the Afer-Sales Department in the Retail Sector, I want 5 KPIs with their formulas for Call Center Performance meausring"

insert_data = '''
INSERT INTO question (id, question)
VALUES (%s, %s)
'''
cursor.execute(insert_data, (id, question))

1

In [36]:
sql = '''SELECT * FROM question'''
cursor.execute(sql)
my_question = cursor.fetchall()
db_question = pd.DataFrame(my_question)
db_question

,id_question,id,question,question_time,id_project
0,1,1,You are a business analyst expert. I am a Cust...,2025-03-02 16:49:07,1
1,2,1,You are a business analyst expert. I am a Cust...,2025-03-02 16:50:33,2
2,3,2,You are a business analyst expert. I am a Cust...,2025-03-02 16:55:50,3
3,4,2,You are a business analyst expert. I am a Cust...,2025-03-02 16:56:25,4
4,5,3,You are a business analyst expert. I am a Cust...,2025-03-02 16:57:00,5

In [131]:
sql = '''SELECT * FROM project'''
cursor.execute(sql)
my_question = cursor.fetchall()
db_question = pd.DataFrame(my_question)
db_question

   id_user  id_project                               project
0   621667           1  Call center tracking and improvement

In [38]:
# answer
id = 1
answer = "here are your 5 kpis"

insert_data = '''
INSERT INTO answer (id, answer)
VALUES (%s, %s)
'''
cursor.execute(insert_data, (id, answer))

1

In [37]:
sql = '''SELECT * FROM answer'''
cursor.execute(sql)
my_answer = cursor.fetchall()
db_answer = pd.DataFrame(my_answer)
db_answer

,id_answer,id_question,id,answer,answer_time
0,1,1,1,"Absolutely, I'd be happy to help you with that...",2025-03-02 16:49:14
1,2,2,1,"Absolutely, I'd be happy to help you with that...",2025-03-02 16:50:39
2,3,3,2,"Absolutely, I'd be happy to help you with that...",2025-03-02 16:55:55
3,4,4,2,"Absolutely, I'd be happy to help with that. He...",2025-03-02 16:56:30
4,5,5,3,"Absolutely, I'd be happy to help you with that...",2025-03-02 16:57:06

In [13]:
prompt = "What is the best French cheese?"
answer = ''' 
The \"best\" French cheese can vary greatly depending on personal taste preferences. However, some of the most famous and highly 
regarded French cheeses include Brie de Meaux, Camembert de Normandie, Roquefort, Comté, 
and Époisses. Each of these cheeses has a unique flavor profile and texture. It's recommended to try a variety to find your personal favorite.
'''
insert_data = '''
INSERT INTO session (prompt, answer) 
VALUES (%s, %s)
'''
cursor.execute(insert_data, (prompt, answer))

1

In [17]:
sql = '''SELECT * FROM session'''
cursor.execute(sql)
my_list = cursor.fetchall()
db_pandas = pd.DataFrame(my_list)
db_pandas

,id,prompt,answer,date
0,1,You are a business analyst expert. I am a cust...,"Absolutely, I'd be happy to help you with that...",2025-02-28 18:04:46
1,2,You are a business analyst expert. I am a cust...,"Absolutely, I'd be happy to help with that. He...",2025-02-28 18:20:13
2,3,You are a business analyst expert. I am a cust...,"Absolutely, I'd be happy to help. Here are fiv...",2025-02-28 18:22:04

In [ ]:
query = "SELECT * FROM session"
cursor.execute(query)
results = cursor.fetchall()

# Devolver los resultados
print(results)

Clean all registered records created while testing

In [48]:
delete_session()

All sessions deleted and AUTO_INCREMENT reset to 1.

In [26]:
sql = '''DROP TABLE answer'''
cursor.execute(sql)
db.commit()